config/routes.rb
Rails.application.routes.draw do
  root                to: 'searches#top'
  get 'around_shops', to: 'searches#around_shops'
  resource :shop, only: [:show]
  resources :reviews, only: [:index, :create, :update, :destroy] do
    collection do
      get 'current_reviews', action: 'current_index'
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/views/shared/_card.html.erb
<div class="row search-result-wrapper">
  <% shops.each_with_index do |shop, i| %>
    <div class="card-content">
      <%= link_to shop_path(shop_id: shop["id"]) do %>
        <div class="card col-12 card-frame <%= "align-center" if current_page?(around_shops_path) %>">
          <input type="hidden" id="lat<%= i %>" value="<%= shop["lat"] %>">
          <input type="hidden" id="lng<%= i %>" value="<%= shop["lng"] %>">
          <div class="g-0 card-wrapper">
            <div class="card-img-wrapper">
              <%= image_tag "#{shop["photo"]["pc"]["l"]}", class: "#{current_page?(around_shops_path) ? "shop-img-lg" : "shop-img-sm"}", alt: "#{shop["name"]}の写真" %>
              <p class="text-muted img-provided">画像提供:ホットペッパー グルメ</p>
            </div>
            <div class="card-body">
              <p class="card-genre">
                <%= shop["genre"]["name"] %>
              </p>
              <h5 class="card-title" id="shopname<%= i %>">
                <%= shop["name"] %>
              </h5>
              <div class="card-area-access">
                <p class="card-area-name">
                  <%= shop["large_area"]["name"] %>
                </p>
                <p class="card-access">
                  <%= shop["mobile_access"] %>
                </p>
              </div>
              <p class="card-text">
                <%= shop["catch"] %>
              </p>
              <div class="card-rate-wrapper">
                <div id="search-rate-<%= shop["id"] %>"></div>
                <span><%= Review.reviews_average(shop["id"]) %></span>
                <div class="reviews-count">
                  <i class="far fa-comments"></i>
                  <p><%= Review.reviews_count(shop["id"]) %>件</p>
                </div>
                <%= render "searches/search_rate", shop: shop %>
              </div>
              <% if current_page?(around_shops_path) && Review.represent_review(shop["id"]).present? %>
                <div class="represent-review">
                  <p><%= Review.represent_review(shop["id"])[0] %></p>
                  <p><%= truncate(Review.represent_review(shop["id"])[1], length: 25) %></p>
                </div>
              <% end %>
            </div>
          </div>
          <% if current_page?(around_shops_path) %>
            <div class="shop-marker-num fa-stack">
              <i class="fas fa-map-marker fa-stack-2x"></i>
              <p class="fa-stack-1x"><%= i + 1 %></p>
            </div>
          <% elsif current_page?(favorites_path) %>
            <object class="favorite-delete">
              <%= link_to favorite_path(shop_id: shop["id"], id: current_user.favorite_id(shop["id"])), data: { confirm: 'お気に入りから削除しますか?' }, method: :delete do %>
                <i class="fas fa-bookmark"></i>
              <% end %>
            </object>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= render "shared/hotpepper_credit"%>

app/views/shared/_edit_modal.html.erb
<div class="modal fade" id="reviewEditModal<%= review.id %>" tabindex="-1" aria-labelledby="reviewEditModalLabel<%= review.id %>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-container">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reviewEditModalLabel<%= review.id %>">口コミ編集</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(model: review, local: false) do |f| %>
        <div class="modal-body">
          <div id="edit-error">
            <%= render "devise/shared/error_messages", resource: f.object %>
          </div>
          <div class="form-group" id="re-star-<%= review.id %>">
            <%= f.label :rate, "評価" %>
            <%= f.hidden_field :rate, id: :review_star %>
          </div>
          <div class="form-group">
            <%= f.text_field :title, class: "form-control review-form", placeholder: "タイトルを入力してください" %>
          </div>
          <div class="form-group">
            <%= f.text_area :comment, class: "form-control review-form", placeholder: "本文を入力してください" %>
          </div>
          <div class="form-group review-images-form">
            <%= f.label :images, '写真' %>
            <%= f.file_field :images, multiple: true %>
          </div>
          <% if review.images.attached? %>
            <div class="review-images-frame">
              <p class="attached-images-title">現在登録されている写真（削除するものはチェックしてください）</p>
              <div class="review-images">
                <% review.images.each do |image| %>
                  <div class="review-image-wrapper">
                    <%= image_tag image.variant(gravity: :center, resize:"130x130^", crop:"130x130+0+0") %>
                    <div class="review-image-checkbox">
                      <%= f.check_box :image_ids, {multiple: true}, image.id, false %>
                      <p>削除する</p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn md-btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          <%= f.submit "更新する", class: "btn md-btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_edit_star_rate.html.erb
<script>
  $("#star-rate<%= review.id %>").raty({
    size: 36,
    starOff: "star-off.png",
    starOn: "star-on.png",
    starHalf: "star-half.png",
    half: true,
    readOnly: true,
    score: "<%= review.rate %>",
  });
  $("#re-star-<%= review.id %>").raty({
    size: 36,
    starOff: "star-off.png",
    starOn: "star-on.png",
    starHalf: "star-half.png",
    scoreName: "review[rate]",
    half: true,
    score: "<%= review.rate %>"
  });
</script>

app/views/shared/_flash.html.erb
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer class="footer">
  <p>Copyright &copy; 2022 WAN SEARCH</p>
</footer>

app/views/shared/_header.html.erb
<!-- HEADER -->
<header>
  <div class="header-container">
    <div class="header-left-nav">
      <%= link_to root_path, class: "header-logo" do %>
        <%= image_tag '/wan-search-logo.png', class: 'header-logo-img' %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="header-right-nav">
        <div class="right-nav-wrapper">
          <%= link_to "最新の口コミ", current_reviews_reviews_path, class: "header-btn md-btn" %>
          <div class="line"></div>
          <%= link_to "お気に入り一覧", favorites_path, class: "header-btn md-btn" %>
          <div class="line"></div>
          <%= link_to "マイページ", edit_user_registration_path, class: "header-btn md-btn" %>
          <div class="line"></div>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-btn md-btn" %>
        </div>
        <div class="current-user-img">
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar.variant(gravity: :center, resize:"300x300^", crop:"300x300+0+0"), id: "current-user-img" %>
          <% else %>
            <%= image_tag "/default_icon.jpg", id: "current-user-img" %>
          <% end %>
        </div>
        <div class="openbtn"><span></span><span></span><span></span></div>
        <nav id="g-nav">
          <ul class="header-nav-menu" id="nav-menu">
            <li>
              <%= link_to "最新の口コミ", current_reviews_reviews_path %>
            </li>
            <li>
              <%= link_to "お気に入り一覧", favorites_path %>
            </li>
            <li>
              <%= link_to "マイページ", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </nav>
      </div>
    <% else %>
      <div class="header-right-nav">
        <div class="right-nav-wrapper">
          <%= link_to "最新の口コミ", current_reviews_reviews_path, class: "header-btn md-btn" %>
          <div class="line"></div>
          <%= link_to "ログイン", new_user_session_path, class: "btn header-btn md-btn" %>
          <div class="line"></div>
          <%= link_to "登録する", new_user_registration_path, class: "btn header-btn md-btn" %>
        </div>
      </div>
      <div class="openbtn"><span></span><span></span><span></span></div>
      <nav id="g-nav">
        <ul class="header-nav-menu" id="nav-menu">
          <li>
            <%= link_to "最新の口コミ", current_reviews_reviews_path %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path %>
          </li>
          <li>
            <%= link_to "登録する", new_user_registration_path %>
          </li>
        </ul>
      </nav>
    <% end %>
  </div>
</header>

app/views/shared/_hotpepper_credit.html.erb
<div class="api-credit">
  <%= link_to image_tag("https://webservice.recruit.co.jp/banner/hotpepper-s.gif", alt: "ホットペッパー Webサービス", width: 135, height: 17, border: 0, title: "ホットペッパー Webサービス" ), "https://webservice.recruit.co.jp/" %>
</div>

app/views/shared/_sidebar.html.erb
<div class="side-bar-wrapper">
  <ul>
    <%= link_to edit_user_registration_path do %>
      <li class="side-bar-link <%= "active" if current_page?(edit_user_registration_path) %>">
        アカウント情報
      </li>
    <% end %>
    <%= link_to favorites_path do %>
      <li class="side-bar-link <%= "active" if current_page?(favorites_path) %>">
        お気に入り一覧
      </li>
    <% end %>
    <%= link_to  reviews_path do %>
      <li class="side-bar-link <%= "active" if current_page?(reviews_path) %>">
        マイレビュー
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_star_rate.html.erb
<div id="star-rate-<%= shop_id %>"></div>
<span><%= reviews.average(:rate).to_f.round(1) %></span>
<div class="reviews-count">
  <i class="far fa-comments"></i>
  <p><%= reviews.count %>件</p>
</div>
<script>
  $('#star-rate-<%= shop_id %>').raty({
    size: 10,
    starOff:  "star-off.png",
    starOn : "star-on.png",
    starHalf: "star-half.png",
    half: true,
    readOnly: true,
    score: "<%= reviews.average(:rate).to_f.round(1) %>",
  });
</script>