config/routes.rb
Rails.application.routes.draw do
  root                to: 'searches#top'
  get 'around_shops', to: 'searches#around_shops'
  resource :shop, only: [:show]
  resources :reviews, only: [:index, :create, :update, :destroy] do
    collection do
      get 'current_reviews', action: 'current_index'
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:current_index]
  before_action :where_access_from, only: [:update, :destroy]
  CURRENT_REVIEW_MAX_NUMBER = 10

  def index
    @my_reviews = Review.includes([images_attachments: :blob]).where(user_id: current_user.id)
  end

  def current_index
    @reviews = Review.includes([images_attachments: :blob], user: [:avatar_attachment]).order(created_at: "DESC").limit(CURRENT_REVIEW_MAX_NUMBER)
  end

  def create
    @review = Review.new(review_params)
    @shop_id = params[:review][:shop_id]
    @reviews = Review.where(shop_id: @shop_id).order(created_at: "DESC")
    if @review.save
      flash.now[:notice] = "口コミを投稿しました"
      respond_to do |format|
        format.html { redirect_to shop_path(shop_id: @shop_id) }
        format.js
      end
    else
      render "review_error"
    end
  end

  def update
    @review = Review.find(params[:id])
    @shop_id = @review.shop_id
    @reviews = Review.where(shop_id: @shop_id).order(created_at: "DESC")
    @my_reviews = Review.where(user_id: current_user.id)
    if params[:review][:image_ids]
      params[:review][:image_ids].each do |image_id|
        image = @review.images.find(image_id)
        image.purge
      end
    end
    if @review.update(review_params)
      flash.now[:notice] = "口コミを編集しました"
      respond_to do |format|
        format.html { redirect_to shop_path(shop_id: @shop_id) }
        format.js
      end
    else
      render "review_error"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review_id = @review.id
    @shop_id = @review.shop_id
    @reviews = Review.where(shop_id: @shop_id).order(created_at: "DESC")
    @my_reviews = Review.where(user_id: current_user.id)
    @review.destroy
    flash.now[:notice] = "投稿を削除しました"
    respond_to do |format|
      format.html { redirect_to shop_path(shop_id: @review.shop_id) }
      format.js
    end
  end

  private
  def review_params
    params.require(:review).permit(:comment, :title, :shop_id, :shop_name, :user_id, :rate, images: [])
  end

  def where_access_from
    @path = Rails.application.routes.recognize_path(request.referer)
  end
end

app/views/reviews/_my_review_index.html.erb
<h1>マイレビュー一覧</h1>
<% if reviews.present? %>
  <% reviews.each do |review| %>
    <div class="review-frame" id="rv-wrapper-<%= review.id %>">
      <div class="review-shop-header">
        <div class="review-shop-name">
          <%= link_to shop_path(shop_id: review.shop_id) do%>
            <%= review.shop_name %>
          <% end %>
        </div>
        <div class="raview-rate-wrapper">
          <div id="star-rate<%= review.id %>"></div>
          <span><%= review.rate %></span>
        </div>
      </div>
      <div class="review-main-content">
        <h5 class="rv-title" id="rv-title-<%= review.id %>"><%= review.title %></h5>
        <p class="rv-comment" id="rv-comment-<%= review.id %>"><%= safe_join(review.comment.split("\n"),tag(:br)) %></p>
        <% if review.images.attached? %>
          <div class="review-images-area">
            <% review.images.each do |image| %>
              <div class="image-opacity">
                <%= link_to url_for(image) do %>
                  <%= image_tag image.variant(gravity: :center, resize:"150x150^", crop:"150x150+0+0") %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="edit-delete-btn">
          <span data-bs-toggle="modal" data-bs-target="#reviewEditModal<%= review.id %>">
            <i class="far fa-edit"></i>
          </span>
          <%= link_to review_path(review), data: { confirm: '削除しますか?' }, class: "review-delete-btn", method: :delete, remote: true do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
    </div>
    <%= render "shared/edit_modal", review: review %>
    <%= render "shared/edit_star_rate", review: review %>
  <% end %>
<% else %>
  <div class="review-inner">
    <p class="no-review">現在クチコミはありません</p>
  </div>
<% end %>

app/views/reviews/_reviews.html.erb
<div class="shop-review-frame">
  <div class="shop-review-title">
    <%= image_tag "/review-image.png" %>
    <h5>みんなの口コミ</h5>
    <% if reviews.exists? && user_signed_in? %>
      <button type="button" class="btn md-btn btn-primary" data-bs-toggle="modal" data-bs-target="#reviewModal">
        口コミを投稿する
      </button>
    <% elsif reviews.exists? %>
      <%= link_to "口コミを投稿する", new_user_session_path, class: "btn-primary md-btn btn" %>
    <% end %>
  </div>
  <div class="review-wrapper">
    <% if reviews.present? %>
      <div class="review-inner" id="reviews">
        <% reviews.each do |review| %>
          <div class="review-frame" id="rv-wrapper-<%= review.id %>">
            <div class="review-user-header">
              <div class="review-user-icon">
                <% if review.user.avatar.attached? %>
                  <%= image_tag review.user.avatar.variant(gravity: :center, resize:"300x300^", crop:"300x300+0+0") %>
                <% else %>
                  <%= image_tag "/default_icon.jpg" %>
                <% end %>
              </div>
              <div class="review-user-name">
                <%= review.user.name %>さんの口コミ
              </div>
              <div class="raview-rate-wrapper">
                <div id="star-rate<%= review.id %>"></div>
                <span><%= review.rate %></span>
              </div>
            </div>
            <div class="review-main-content">
              <h5 class="rv-title" id="rv-title-<%= review.id %>"><%= review.title %></h5>
              <p class="rv-comment" id="rv-comment-<%= review.id %>"><%= safe_join(review.comment.split("\n"),tag(:br)) %></p>
                <% if review.images.attached? %>
                  <div class="review-images-area">
                    <% review.images.each do |image| %>
                      <div class="image-opacity">
                        <%= link_to url_for(image) do %>
                          <%= image_tag image.variant(gravity: :center, resize:"150x150^", crop:"150x150+0+0") %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <div class="edit-delete-btn">
                <% if user_signed_in? && current_user.id == review.user_id %>
                  <span data-bs-toggle="modal" data-bs-target="#reviewEditModal<%= review.id %>">
                    <i class="far fa-edit"></i>
                  </span>
                  <%= link_to review_path(review), data: { confirm: '削除しますか?' }, class: "review-delete-btn", method: :delete, remote: true do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <%= render "shared/edit_modal", review: review %>
          <%= render "shared/edit_star_rate", review: review %>
        <% end %>
      </div>
    <% else %>
      <div class="review-inner" id="reviews">
        <p>現在クチコミはありません</p>
        <% if user_signed_in? %>
          <button type="button" class="btn lg-btn btn-primary mt-4" data-bs-toggle="modal" data-bs-target="#reviewModal">
            口コミを投稿する
          </button>
        <% else %>
          <%= link_to "口コミを投稿する", new_user_session_path, class: "btn lg-btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/hotpepper_credit" %>

app/views/reviews/create.js.erb
$(function(){
  $(".review-form").val("");
  $("#review-error").remove();
  $("#reviewModal").modal("hide");
  $("#flash-message").html("<%= j(render "shared/flash") %>");
  $("#shop-avg-rate").html("<%= j(render "shared/star_rate", shop_id: @shop_id, reviews: @reviews) %>");
  $("#shop-review-content").html("<%= j(render"reviews", reviews: @reviews) %>");
})

app/views/reviews/current_index.html.erb
<% provide(:title, "最新口コミ") %>
<div class="container">
  <div class="cuurent-review-frame">
    <div class="shop-review-title">
      <%= image_tag "/review-image.png" %>
      <h5>みんなの最新口コミ</h5>
    </div>
    <div class="review-wrapper">
      <% if @reviews.present? %>
        <div class="review-inner" id="reviews">
          <% @reviews.each do |review| %>
            <div class="review-frame" id="rv-wrapper-<%= review.id %>">
              <div class="current-review-shop-name">
                <%= link_to shop_path(shop_id: review.shop_id) do%>
                  <%= review.shop_name %>
                <% end %>
              </div>
              <div class="review-user-header">
                <div class="review-user-icon">
                  <% if review.user.avatar.attached? %>
                    <%= image_tag review.user.avatar.variant(gravity: :center, resize:"300x300^", crop:"300x300+0+0") %>
                  <% else %>
                    <%= image_tag "/default_icon.jpg" %>
                  <% end %>
                </div>
                <div class="review-user-name">
                  <%= review.user.name %>さんの口コミ
                </div>
                <div class="raview-rate-wrapper">
                  <div id="star-rate<%= review.id %>"></div>
                  <span><%= review.rate %></span>
                </div>
              </div>
              <div class="review-main-content">
                <h5 class="rv-title" id="rv-title-<%= review.id %>"><%= review.title %></h5>
                <p class="rv-comment" id="rv-comment-<%= review.id %>"><%= safe_join(review.comment.split("\n"),tag(:br)) %></p>
                <% if review.images.attached? %>
                  <div class="review-images-area">
                    <% review.images.each do |image| %>
                      <div class="image-opacity">
                        <%= link_to url_for(image) do %>
                          <%= image_tag image.variant(gravity: :center, resize:"150x150^", crop:"150x150+0+0") %>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
            <script>
              $("#star-rate<%= review.id %>").raty({
                size: 36,
                starOff: "/star-off.png",
                starOn: "/star-on.png",
                starHalf: "/star-half.png",
                half: true,
                readOnly: true,
                score: "<%= review.rate %>",
              });
            </script>
          <% end %>
        </div>
      <% else %>
        <div class="review-inner" id="reviews">
          <p>現在クチコミはありません</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/destroy.js.erb
<% if @path[:controller] == "shops" && @path[:action] == "show" %>
  $(function(){
    $("#shop-review-content").html("<%= j(render"reviews", reviews: @reviews) %>");
    $("#flash-message").html("<%= j(render "shared/flash") %>");
    $("#shop-avg-rate").html("<%= j(render "shared/star_rate", shop_id: @shop_id, reviews: @reviews) %>");
  })
<% elsif @path[:controller] == "reviews" && @path[:action] == "index" %>
    $(function(){
    $("#user-review-inner").html("<%= j(render "my_review_index", reviews: @my_reviews) %>");
    $("#flash-message").html("<%= j(render "shared/flash") %>");
  })
<% end %>

app/views/reviews/error.js.erb
<% case controller.action_name %>
<% when "create" %>
  $(function(){
    $("#review-error").html("<%= j(render "devise/shared/error_messages", resource: @review) %>");
  })
<% when "update" %>
  $(function(){
    $("#edit-error").html("<%= j(render "devise/shared/error_messages", resource: @review) %>");
  })
<% end %>

app/views/reviews/index.html.erb
<% provide(:title,  "マイレビュー一覧") %>
<div class="user-review-wrapper">
  <%= render "shared/sidebar" %>
  <div class="user-review-inner" id="user-review-inner">
    <%= render "my_review_index", reviews: @my_reviews %>
  </div>
</div>

app/views/reviews/review_error.js.erb
<% case controller.action_name %>
<% when "create" %>
  $(function(){
    $("#review-error").html("<%= j(render "devise/shared/error_messages", resource: @review) %>");
  })
<% when "update" %>
  $(function(){
    $("#edit-error").html("<%= j(render "devise/shared/error_messages", resource: @review) %>");
  })
<% end %>

app/views/reviews/update.js.erb
<% if @path[:controller] == "shops" && @path[:action] == "show" %>
  $(function(){
    $(".review-form").val("");
    $("#review-error").remove();
    $("#reviewEditModal<%= @review.id %>").modal("hide");
    $("#flash-message").html("<%= j(render "shared/flash") %>");
    $("#shop-avg-rate").html("<%= j(render "shared/star_rate", shop_id: @shop_id, reviews: @reviews) %>");
    $("#shop-review-content").html("<%= j(render "reviews", reviews: @reviews) %>");
  })
<% elsif @path[:controller] == "reviews" && @path[:action] == "index" %>
  $(function(){
    $(".review-form").val("");
    $("#review-error").remove();
    $("#reviewEditModal<%= @review.id %>").modal("hide");
    $("#flash-message").html("<%= j(render "shared/flash") %>");
    $("#user-review-inner").html("<%= j(render "my_review_index", reviews: @my_reviews) %>");
  })
<% end %>